curie_map:
  MONDO: http://purl.obolibrary.org/obo/MONDO_
  UMLS: http://linkedlifedata.com/resource/umls/id/
  NCIT: http://purl.obolibrary.org/obo/NCIT_
  DOID: http://purl.obolibrary.org/obo/DOID_
  EFO: http://www.ebi.ac.uk/efo/EFO_
  HGNC: "http://identifiers.org/hgnc/"
  # HGNC__2: "https://identifiers.org/hgnc:"
  # HGNC__3: "https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:"
  # HGNC_symbol: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/
  HP: http://purl.obolibrary.org/obo/HP_
  # SCTID: http://identifiers.org/snomedct/
  # SCTID__2: http://snomed.info/id/
  OMIM: https://omim.org/entry/
  # OMIM__2: http://identifiers.org/omim/
  # OMIM__3: http://purl.obolibrary.org/obo/OMIM_
  # OMIM__4: http://omim.org/entry/
  mesh: http://identifiers.org/mesh/
  Orphanet: http://www.orpha.net/ORDO/Orphanet_
  # Orphanet__2: https://www.orpha.net/ORDO/Orphanet_
  # Orphanet__3: http://purl.obolibrary.org/obo/Orphanet_
  oboInOwl: http://www.geneontology.org/formats/oboInOwl#
  NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
  skos: http://www.w3.org/2004/02/skos/core#
  ICD10CM: http://purl.bioontology.org/ontology/ICD10CM/
  # ICD10CM__2: https://icd.codes/icd10cm/
  # ICD10WHO: https://icd.who.int/browse10/2019/en#/
  # ICD10WHO__2: http://apps.who.int/classifications/icd10/browse/2010/en#/
  OMIMPS: https://omim.org/phenotypicSeries/PS
  MEDGEN: http://identifiers.org/medgen/
  MedDRA: http://identifiers.org/meddra/
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  owl: http://www.w3.org/2002/07/owl#
  semapv: https://w3id.org/semapv/vocab/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  sssom: https://w3id.org/sssom/
  # oio: http://www.geneontology.org/formats/oboInOwl#
  GTR: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/GTR/"
  # NCI: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/NCI/"
  NIFSTD: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/NIFSTD/"
  PO_GIT: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/PO_GIT/"
  CALOHA: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/CALOHA/"
  Reactome: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/Reactome/"
  MTH: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/MTH/"
  IMDRF: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/IMDRF/"
  LOINC: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/LOINC/"
  MEDDRA: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/MEDDRA/"
  # ncithesaurus: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ncithesaurus/"
  COHD: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/COHD/"
  ONCOTREE: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ONCOTREE/"
  ICD9: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD9/"
  NDFRT: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/NDFRT/"
  ICD9CM: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD9CM/"
  SUBSET_SIREN: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/SUBSET_SIREN/"
  ICDO: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICDO/"
  Wikidata: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/Wikidata/"
  IEDB: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/IEDB/"
  PMID: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/PMID/"
  KEGG: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/KEGG/"
  ICD11: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD11/"
  DECIPHER: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/DECIPHER/"
  CSP: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/CSP/"
  Wikipedia: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/Wikipedia/"
  Fyler: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/Fyler/"
  EPCC: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/EPCC/"
  # UMLS_CUI: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/UMLS_CUI/"
  KUPO: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/KUPO/"
  OMOP: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/OMOP/"
  # ICD10: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD10/"
  ICD10EXP: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD10EXP/"
  DERMO: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/DERMO/"
  GARD: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/GARD/"
  # SNOMEDCT_US: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/SNOMEDCT_US/"
  # MSH: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/MSH/"
  GC_ID: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/GC_ID/"
  # SNOMEDCT_2010_1_31: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/SNOMEDCT_2010_1_31/"
  OMIA: "http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/OMIA/"

extended_prefix_map:
  - prefix: MONDO
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/MONDO_
    uri_prefix_synonyms: []
  - prefix: UMLS
    prefix_synonyms: []
    uri_prefix: http://linkedlifedata.com/resource/umls/id/
    uri_prefix_synonyms: []
  - prefix: NCIT
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/NCIT_
    uri_prefix_synonyms: []
  - prefix: DOID
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/DOID_
    uri_prefix_synonyms: []
  - prefix: EFO
    prefix_synonyms: []
    uri_prefix: http://www.ebi.ac.uk/efo/EFO_
    uri_prefix_synonyms: []
  - prefix: HGNC
    prefix_synonyms: []
    uri_prefix: http://identifiers.org/hgnc/
    uri_prefix_synonyms:
      - 'https://identifiers.org/hgnc:'
      - 'https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:'
  - prefix: HGNC_symbol
    prefix_synonyms: []
    uri_prefix: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/
    uri_prefix_synonyms: []
  - prefix: HP
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/HP_
    uri_prefix_synonyms: []
  - prefix: SCTID
    prefix_synonyms: []
    uri_prefix: http://identifiers.org/snomedct/
    uri_prefix_synonyms:
      - http://snomed.info/id/
  - prefix: OMIM
    prefix_synonyms: []
    uri_prefix: https://omim.org/entry/
    uri_prefix_synonyms:
      - http://identifiers.org/omim/
      - http://purl.obolibrary.org/obo/OMIM_
      - http://omim.org/entry/
  - prefix: MESH
    prefix_synonyms: []
    uri_prefix: http://identifiers.org/mesh/
    uri_prefix_synonyms: []
  - prefix: Orphanet
    prefix_synonyms: []
    uri_prefix: http://www.orpha.net/ORDO/Orphanet_
    uri_prefix_synonyms:
      - https://www.orpha.net/ORDO/Orphanet_
      - http://purl.obolibrary.org/obo/Orphanet_
  - prefix: oboInOwl
    prefix_synonyms:
    - oio
    uri_prefix: http://www.geneontology.org/formats/oboInOwl#
    uri_prefix_synonyms: []
  - prefix: NCBITaxon
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/NCBITaxon_
    uri_prefix_synonyms: []
  - prefix: skos
    prefix_synonyms: []
    uri_prefix: http://www.w3.org/2004/02/skos/core#
    uri_prefix_synonyms: []
  - prefix: ICD10CM
    prefix_synonyms: []
    uri_prefix: http://purl.bioontology.org/ontology/ICD10CM/
    uri_prefix_synonyms:
      -  https://icd.codes/icd10cm/
  - prefix: ICD10WHO
    prefix_synonyms: []
    uri_prefix: https://icd.who.int/browse10/2019/en#/
    uri_prefix_synonyms:
      - http://apps.who.int/classifications/icd10/browse/2010/en#/
  - prefix: OMIMPS
    prefix_synonyms: []
    uri_prefix: https://omim.org/phenotypicSeries/PS
    uri_prefix_synonyms: []
  - prefix: MEDGEN
    prefix_synonyms: []
    uri_prefix: http://identifiers.org/medgen/
    uri_prefix_synonyms: []
  - prefix: MedDRA
    prefix_synonyms: []
    uri_prefix: http://identifiers.org/meddra/
    uri_prefix_synonyms: []
  - prefix: rdfs
    prefix_synonyms: []
    uri_prefix: http://www.w3.org/2000/01/rdf-schema#
    uri_prefix_synonyms: []
  - prefix: owl
    prefix_synonyms: []
    uri_prefix: http://www.w3.org/2002/07/owl#
    uri_prefix_synonyms: []
  - prefix: semapv
    prefix_synonyms: []
    uri_prefix: https://w3id.org/semapv/vocab/
    uri_prefix_synonyms: []
  - prefix: rdf
    prefix_synonyms: []
    uri_prefix: http://www.w3.org/1999/02/22-rdf-syntax-ns#
    uri_prefix_synonyms: []
  - prefix: sssom
    prefix_synonyms: []
    uri_prefix: https://w3id.org/sssom/
    uri_prefix_synonyms: []
  - prefix: GTR
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/GTR/
    uri_prefix_synonyms: []
  - prefix: NCI
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/NCI/
    uri_prefix_synonyms: []
  - prefix: NIFSTD
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/NIFSTD/
    uri_prefix_synonyms: []
  - prefix: PO_GIT
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/PO_GIT/
    uri_prefix_synonyms: []
  - prefix: CALOHA
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/CALOHA/
    uri_prefix_synonyms: []
  - prefix: Reactome
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/Reactome/
    uri_prefix_synonyms: []
  - prefix: MTH
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/MTH/
    uri_prefix_synonyms: []
  - prefix: IMDRF
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/IMDRF/
    uri_prefix_synonyms: []
  - prefix: LOINC
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/LOINC/
    uri_prefix_synonyms: []
  - prefix: MEDDRA
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/MEDDRA/
    uri_prefix_synonyms: []
  - prefix: ncithesaurus
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ncithesaurus/
    uri_prefix_synonyms: []
  - prefix: COHD
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/COHD/
    uri_prefix_synonyms: []
  - prefix: ONCOTREE
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ONCOTREE/
    uri_prefix_synonyms: []
  - prefix: ICD9
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD9/
    uri_prefix_synonyms: []
  - prefix: NDFRT
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/NDFRT/
    uri_prefix_synonyms: []
  - prefix: ICD9CM
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD9CM/
    uri_prefix_synonyms: []
  - prefix: SUBSET_SIREN
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/SUBSET_SIREN/
    uri_prefix_synonyms: []
  - prefix: ICDO
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICDO/
    uri_prefix_synonyms: []
  - prefix: Wikidata
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/Wikidata/
    uri_prefix_synonyms: []
  - prefix: IEDB
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/IEDB/
    uri_prefix_synonyms: []
  - prefix: PMID
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/PMID/
    uri_prefix_synonyms: []
  - prefix: KEGG
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/KEGG/
    uri_prefix_synonyms: []
  - prefix: ICD11
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD11/
    uri_prefix_synonyms: []
  - prefix: DECIPHER
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/DECIPHER/
    uri_prefix_synonyms: []
  - prefix: CSP
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/CSP/
    uri_prefix_synonyms: []
  - prefix: Wikipedia
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/Wikipedia/
    uri_prefix_synonyms: []
  - prefix: Fyler
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/Fyler/
    uri_prefix_synonyms: []
  - prefix: EPCC
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/EPCC/
    uri_prefix_synonyms: []
  - prefix: UMLS_CUI
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/UMLS_CUI/
    uri_prefix_synonyms: []
  - prefix: KUPO
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/KUPO/
    uri_prefix_synonyms: []
  - prefix: OMOP
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/OMOP/
    uri_prefix_synonyms: []
  - prefix: ICD10
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD10/
    uri_prefix_synonyms: []
  - prefix: ICD10EXP
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/ICD10EXP/
    uri_prefix_synonyms: []
  - prefix: DERMO
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/DERMO/
    uri_prefix_synonyms: []
  - prefix: GARD
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/GARD/
    uri_prefix_synonyms: []
  - prefix: SNOMEDCT_US
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/SNOMEDCT_US/
    uri_prefix_synonyms: []
  - prefix: MSH
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/MSH/
    uri_prefix_synonyms: []
  - prefix: GC_ID
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/GC_ID/
    uri_prefix_synonyms: []
  - prefix: SNOMEDCT_2010_1_31
    prefix_synonyms: []
    uri_prefix: http://purl.obolibrary.org/obo/mondo/mappings/unknown_prefix/SNOMEDCT_2010_1_31/
    uri_prefix_synonyms: []

subject_prefixes:
  - MONDO
  - OMIM
  - Orphanet
  - EFO
  - ICD10CM
  - ICD10WHO
  - OMIMPS
  - NCIT
  - DOID
relations:
  - oboInOwl:hasDbXref
  - skos:exactMatch
  - skos:broadMatch
  - skos:narrowMatch
  - skos:closeMatch
  - skos:relatedMatch
global_metadata:
  subject_source: http://purl.obolibrary.org/obo/mondo.owl
  license: "https://creativecommons.org/publicdomain/zero/1.0/"
  mapping_date: "2017-09-20"
  mapping_set_id: "GLOBAL" # Apparently this is the one that matters.
source_metadata:
  - from: MONDO
    to: OMIM
    metadata:
      object_source: https://www.omim.org/
      object_source_version: http://www.orphadata.org/data/ORDO/ordo_orphanet_3.1.owl
      mapping_date: "2022-02-11"
      comment: "The latest OMIM is integrated with every Mondo release."
  - from: MONDO
    to: UMLS
    metadata:
      object_source: https://uts.nlm.nih.gov/uts/
  - from: MONDO
    to: EFO
    metadata:
      object_source: http://www.ebi.ac.uk/efo/efo.owl
  - from: MONDO
    to: ICD10CM
    metadata:
      object_source: https://www.icd10data.com/
      mapping_date: "2017-09-20"
  - from: MONDO
    to: Orphanet
    metadata:
      object_source: https://www.orpha.net/
      object_source_version: http://www.orphadata.org/data/ORDO/ordo_orphanet_3.1.owl
      mapping_date: "2021-07-06"
      comment: "The latest Orphanet is integrated with every Mondo release."
  - from: MONDO
    to: NCIT
    metadata:
      object_source: http://purl.obolibrary.org/obo/ncit.owl
      object_source_version: http://purl.obolibrary.org/obo/ncit/releases/2018-06-14/ncit.owl
      mapping_date: "2018-06-14"
  - from: MONDO
    to: DOID
    metadata:
      object_source: http://purl.obolibrary.org/obo/doid.owl
      object_source_version: http://purl.obolibrary.org/obo/doid/releases/2018-07-05/doid.owl
      mapping_date: "2018-07-05"
