site_name: Mondo Documentation
docs_dir: docs
site_dir: docs-site
theme:
  name: 'material'
markdown_extensions:
  - toc:
      permalink: True
nav:
  - index.md
  - analysis.md
  - change-log.md
  - set-up-docker.md
  - release.md
  - repair-obsoleted-classes.md
  - a-protege-setup.md
  - b-github-access.md
  - c-make-good-term-request.md 
  - d-github-pr-workflow.md
  - dd-github-conflicts.md
  - diffs.md
  - e-design-patterns.md
  - f-entities.md
  - g-logical-axioms.md
  - import-terms-for-logical-axioms.md
  - imports.md
  - merging-and-obsoleting.md
  - splitting-classes.md
  - mondo-website-editing.md
  - troubleshooting.md
    
