site_name: Mondo Documentation
docs_dir: docs
site_dir: docs-site
theme:
  name: 'material'
extra_css:
  - style.css
markdown_extensions:
  - toc:
      permalink: True
nav:
    - Introduction: index.md
    - Getting ready (set-up):
      - Set up new computer: editors-guide/set-up-new-computer.md
      - GitHub access: editors-guide/b-github-access.md
      - Protege set up: editors-guide/a-protege-setup.md
      - Set up docker: developer-guide/set-up-docker.md
      - Generate token: developer-guide/generate-token.md
    - Mondo Editing (rules and practices):
      - Entities: editors-guide/f-entities.md
      - Revise Terms in Mondo: editors-guide/revise-terms-in-mondo.md
      - Logical axioms: editors-guide/g-logical-axioms.md
      - Merging and obsoleting: editors-guide/merging-and-obsoleting.md
      - Strategic Refinement: editors-guide/strategic-refinement.md
      - Splitting classes: editors-guide/splitting-classes.md
      - Merging a ROBOT template into Mondo: editors-guide/robot-template.md
      - Exclusion reasons: editors-guide/exclusion-reasons.md
      - Design patterns:
        - Design patterns: editors-guide/e-design-patterns.md
        - Patterns: editors-guide/patterns/
      - Bulk Editing Using Regular Expressions: editors-guide/regex.md
      - Annotation Bulk Removal/Update: editors-guide/bulk-removal.md
      - Rare disease subset curation: editors-guide/rare-disease-curator.md
      - Edit Mondo documentation website: editors-guide/mondo-docs-website-editing.md
      - Edit Mondo community website: editors-guide/mondo-website-editing.md
    - Mondo Workflow:
      - GitHub PR workflow: editors-guide/d-github-pr-workflow.md
      - Pre-release checklist: editors-guide/pre-release-checklist.md
      - Release workflow: developer-guide/release.md
      - Imports: editors-guide/imports.md
      - Import terms for logical axioms: editors-guide/import-terms-for-logical-axioms.md
      - Update external sources: editors-guide/update-external-sources.md
      - Ingest source terms into Mondo: editors-guide/synching.md
      - Mondo ingest updates: mondo-ingest-updates.md
      - OMIM Migration: editors-guide/omim-migration.md
      - OMIM included entries: editors-guide/omim-included_entries.md
      - Migration workflow: editors-guide/migration-workflow.md
    - Quality Control and Checks (QC):
      - Quality control: editors-guide/quality-control.md
      - Quality control tests: editors-guide/quality-control-tests.md
      - Generate reports: editors-guide/generate-report.md
      - Add new QC check: developers-guide/add-new-qc-check.md
      - Check for and Merge Duplicate annotations in Mondo: editors-guide/NORM.md
      - Risky obsoletion check: editors-guide/risky_obsoletion_check.md
      - Diffs: editors-guide/diffs.md
      - Remove inferred subclass axiom: developer-guide/remove-inferred-subclass-axiom.md
    - Troubleshooting:
      - Troubleshooting: editors-guide/troubleshooting.md
      - GitHub conflicts: editors-guide/dd-github-conflicts.md
      - Repair obsoleted classes: developer-guide/repair-obsoleted-classes.md
      - Debugging Docs: developer-guide/debugging-docs.md
    - Mondo User Corner:
      - Identifiers: editors-guide/identifiers.md
      - Curation Workflow Overview: editors-guide/curation-workflow-overview.md
      - Download Protege 5.5 and View Mondo Files (Windows): editors-guide/protege-to-view-mondo.md
      - Searching Mondo: editors-guide/searching-mondo.md
      - Make good term request: editors-guide/c-make-good-term-request.md
      - Make multiple term requests in bulk: editors-guide/bulk-request.md
      - Make simple changes: editors-guide/make-simple-changes.md
      - SOP Splitting Terms: editors-guide/sop_splitting-terms.md
      - Mappings: editors-guide/mappings.md
      - Version diff report: editors-guide/version-diff-report.md
      - Using Mondo for Data curation: editors-guide/using-mondo-for-curation.md
      - Sample code: editors-guide/sample-code.md
      - Rare disease subset: editors-guide/rare-disease-subset.md
    - Cite:
      - Cite Mondo: editors-guide/cite.md
    - Project management:
      - Project management guide: editors-guide/project-management.md



