name: Update Externally Provided Content

on:
#  schedule:
#    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5.4

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Update Externally Provided Content
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-external-content-incl-rare -B
    
      - name: Run ontology QC checks
        env:
          DEFAULT_BRANCH: master
        run: cd src/ontology; make GITHUB_ACTION=true IMP=false PAT=false test -B
        continue-on-error: true  # Allow QC to fail but continue

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          branch-suffix: short-commit-hash
          labels: Automated
          body: "Update the externally managed content. This includes all content, including updates to the rare disease subsets."
          title: "Externally managed content update"
          base: ${{ github.head_ref }}
          branch: "externally_managed_content"
          token: ${{ secrets.GH_TOKEN }}
          reviewers: "twhetzel"
